
# Laboratory 3  
**Name:** Rod Vincent Dela Vega

**Section:** DS4A

**Task:** Perform a forward and backward propagation in Python using the inputs from Laboratory Task 2

---

### **Objective**
To perform both forward and backward propagation in a simple neural network using ReLU as the activation function and update the weights accordingly.

### **Given Data**
```python
x = np.array([1, 0, 1])
y = np.array([1])
lr = 0.001
```


In [1]:

import numpy as np

# Input and target
x = np.array([1, 0, 1]).reshape(3, 1)
y = np.array([1]).reshape(1, 1)

# Learning rate
lr = 0.001

# Initialize weights (same as Laboratory 2)
W1 = np.array([[0.2, -0.3],
               [0.4,  0.1],
               [-0.5,  0.2]])

W2 = np.array([[-0.3, -0.2]])

# Biases
theta = np.array([[-0.4], [0.2], [0.1]])


In [2]:

# Forward Propagation

# Hidden layer linear combination
Z = np.dot(W1.T, x) + theta[:2]

# ReLU activation
f = np.maximum(0, Z)

# Output layer (no activation, linear output)
y_hat = np.dot(W2, f)

# Compute loss (mean squared error)
E = 0.5 * (y - y_hat)**2

print("Hidden Input (Z):\n", Z)
print("\nActivated Output (f):\n", f)
print("\nPredicted Output (y_hat):\n", y_hat)
print("\nError (E):\n", E)


Hidden Input (Z):
 [[-0.7]
 [ 0.1]]

Activated Output (f):
 [[0. ]
 [0.1]]

Predicted Output (y_hat):
 [[-0.02]]

Error (E):
 [[0.5202]]


In [4]:

# Backward Propagation

# Derivative of error w.r.t output
dE_dyhat = -(y - y_hat)

# Gradient for W2
dE_dW2 = dE_dyhat * f.T

# Gradient for hidden layer
dE_df = dE_dyhat * W2

# ReLU derivative (0 if Z <= 0 else 1)
dReLU = (Z > 0).astype(float)

# Chain rule to get gradient for W1
dE_dZ = dE_df.T * dReLU
dE_dW1 = np.dot(x, dE_dZ.T)

# Weight Updates
W2_new = W2 - lr * dE_dW2
W1_new = W1 - lr * dE_dW1

print("Gradient for W2:\n", dE_dW2)
print("\nGradient for W1:\n", dE_dW1)
print("\nUpdated W2:\n", W2_new)
print("\nUpdated W1:\n", W1_new)


Gradient for W2:
 [[-0.    -0.102]]

Gradient for W1:
 [[0.    0.204]
 [0.    0.   ]
 [0.    0.204]]

Updated W2:
 [[-0.3      -0.199898]]

Updated W1:
 [[ 0.2      -0.300204]
 [ 0.4       0.1     ]
 [-0.5       0.199796]]



### **Result Summary**
- **Forward Propagation:** Computed the network output and error.  
- **Backward Propagation:** Calculated gradients for each weight using the chain rule.  
- **Weight Update:** Adjusted weights using the learning rate (lr = 0.001).  

This demonstrates how the network learns by minimizing error through gradient descent.
