ROD VINCENT DELA VEGA 

DS4A

Laboratory Task 5
1. Perform Standard Imports


2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value.


3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.


4. Create a tensor "x" from the array above


5. Change the dtype of x from int32 to int64


6. Reshape x into a 3x2 tensor
There are several ways to do this.


7. Return the right-hand column of tensor x


8. Without changing x, return a tensor of square values of x
There are several ways to do this.


9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed.
Think about what shape it should have to permit matrix multiplication.


10. Find the matrix product of x and y.

In [25]:
# 1 Perform Standard Imports
import torch
import numpy as np
import sys
import random

In [26]:
# 2. Create a function called set_seed()
def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)
    random.seed(seed)

In [27]:
# 3. Create NumPy array "arr" with random integers between 0 and 5
set_seed(42)
arr = np.random.randint(0, 5, 6, dtype=np.int64)
print("NumPy array:\n", arr)

NumPy array:
 [3 4 2 4 4 1]


In [28]:
# 4. Create tensor "x" from the array above
x = torch.from_numpy(arr)
print("\nTensor x:\n", x)
print("dtype:", x.dtype)


Tensor x:
 tensor([3, 4, 2, 4, 4, 1])
dtype: torch.int64


In [29]:
# 5. Change dtype of x from int64 to int64 (already int64, but safe to enforce)
x = x.long()  # or x = x.type(torch.int64)
print("\nTensor x (int64):\n", x)
print("dtype:", x.dtype)


Tensor x (int64):
 tensor([3, 4, 2, 4, 4, 1])
dtype: torch.int64


In [30]:
# 6. Reshape x into a 3x2 tensor
x = x.view(3, 2)
print("\nTensor x reshaped (3x2):\n", x)


Tensor x reshaped (3x2):
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [31]:
# 7. Return the right-hand column of tensor x
right_col = x[:, 1]
print("\nRight-hand column:\n", right_col)


Right-hand column:
 tensor([4, 4, 1])


In [32]:
# 8. Without changing x, return a tensor of square values of x
squared = x ** 2
print("\nSquared values of x:\n", squared)


Squared values of x:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [33]:
# 9. Create tensor y with same num of elements as x that can be matrix-multiplied
set_seed(42)
y = torch.randint(0, 5, (2, 3), dtype=torch.int64)  # Match dtype with x
print("\nTensor y (2x3):\n", y)


Tensor y (2x3):
 tensor([[2, 2, 1],
        [4, 1, 0]])


In [34]:
# 10. Matrix product of x and y
matmul_result = x @ y  # or torch.mm(x, y)
print("\nMatrix product (x @ y):\n", matmul_result)


Matrix product (x @ y):
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
